package model

type Guru struct {
	Id                int          // auto generated by DB
	Email             string       // email
	FirstName         string       // first name
	MiddleName        string       // middle name
	LastName          string       // last name
	Gender            string       // male / female / other
	dob               string       // date of birth
	Institution       string       // college/ univ
	Degree            string       // highest degree
	Exp               float32      // years of programming experience
	Language          []string     // languages proefficient and can give coaching
	CurrentCompany    string       // currently working
	PreviousCompanies []string     // previously worked, if any
	PrevSissos        []int        // students coached (just the ids)
	Domain            string       // which domain
	Rating            float32      // rating of the guru
	Price             float32      // fees of the maintor(guru)
	Availability      string       // when available (weekend, weekdays, evenings, mornings)
	Testimonials      []string     // testimonial of the students
	Verified          verification // default [false], after verification -> [true]
}
