package model

type Sisso struct {
	Id            int          // auto generated by DB
	Email         string       // email
	FirstName     string       // first name
	MiddleName    string       // middle name
	LastName      string       // last name
	Gender        string       // male / female / other
	dob           string       // date of birth
	Institution   string       // college or univ
	CurrentDegree string       // pursuing
	Degree        string       // highest degrees
	PrevGurus     []int        // teachers (id's of them)
	Domain        string       // which domain the student is interested in
	Verified      verification // default [false], after vefirication -> [true]
}
